### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#12]
Auto-scaling and elastic balance EdX monolith

**Comment by nicovanniekerk** [comment]
So thus far there has been a lot of dependency miss matches which i have fixed and also found the correct version for edx-pattern-library to not break the insights initial deployment.

current deployment testing shows that i have about 60% clean deployment and it will increase as i go along. i am almost in a place to conclude this fixup and merge the release-testing branch into staging.

Once the full a-z deployment works,  i.e. run ansible and when it says it is done the site is functional, i will split it out into different levels, as to make dev build happen super fast without installing the hole system, nightly full deployment - test builds will also be put into place to gather metrix on the stability of deployments. it would be super to say we can deploy a full system in 3 hours with zero human intervention.

**Comment by nicovanniekerk** [comment]
Progress are looking good and microsite nginx/env  config generation is working and pulled into the release-testing branch. production deployment tested as well and works as expected. next step is to review and merge release-testing branch to staging. Once merged to staging, the setup of ci will begin.

First ci job:
- build as devstack environment, follow edx for example, run all tests and analytics.

second ci job
- nightly full builds, mimic server creation and key placement with circle. 0-hero and then run tests if possible.

**Comment by nicovanniekerk** [comment]
all work has been merged into staging and running a full staging test deployment to replicate success results  if we good a production deployment will be done and if that succeeds as well, I can start with the circle setup for platform

**Comment by nicovanniekerk** [comment]
circle deployment of platform will be put in place alongside the dev server setup

**Comment by nicovanniekerk** [comment]
dev server has been setup and working and part of the process, circle builds in progress and running tests, just takes very very long.

**Comment by nicovanniekerk** [comment]
Finally got to the point where i can run tests and see the results. rest of automation to be done, once all tests are passing again.

**Comment by nicovanniekerk** [comment]
This is still pretty much on hold, due to circle not really playing along. will pick this back up in Jan,

@renevatium @jagonzalr FYI

**Comment by nicovanniekerk** [comment]
this will be setup by EduNext very soon
