### ISSUE TITLE
Enable student certificate generation

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#205]

**Comment by jagonzalr** [comment]
@renevatium following this [link](https://openedx.atlassian.net/wiki/display/OpenOPS/How+to+Enable+On-Demand+Certificate+Download+for+Self-Paced+Courses) it appears that the only thing to do is to create a new [certificate generation configuration](http://localhost:8000/admin/certificates/certificategenerationconfiguration/add/) and set `enabled` to `true`

Then the option of certificates will appear in the instructor panel (only if the current user has the flag `is_staff` to `true`)

<img width="1257" alt="screenshot 2016-10-31 14 05 19" src="https://cloud.githubusercontent.com/assets/3858265/19853627/19dadc20-9f73-11e6-9d04-dccb2cd3b1b7.png">

**Comment by renevatium** [comment]
@jagonzalr have gone through that process already, unfortunately not that easy. There are some config flags that need to be enabled and need to test the UI. Don't worry about this one for now.

**Comment by nicovanniekerk** [comment]
certificates are all good now and is dictated according to the course setup
