### ISSUE TITLE
Instructor email branding

### ISSUE THREAD

**Issue by jagonzalr** [proversity-org/edx-platform#210]
[LeanKit reference](https://proversity.leankit.com/Boards/View/338490398/392828315)
- [x] Create new template in [admin](https://learn.proversity.org/admin/bulk_email/courseemailtemplate/add/)
- [x] Create new [site configuration](https://learn.proversity.org/admin/site_configuration/siteconfiguration/add/) with values:

```
{
  "course_email_template_name":"name_of_template"
}
```

**Comment by nicovanniekerk** [comment]
@jagonzalr we finally did this hahaha. closing it now.
