### ISSUE TITLE
Make libraries ORG specific

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#216]
@renevatium commented on [Mon Jul 04 2016](https://github.com/proversity-org/edx-theme-proversity/issues/10)

Fix libraries to use ORG security process in place for courses. Need to look into library config options.

---

@renevatium commented on [Thu Aug 11 2016](https://github.com/proversity-org/edx-theme-proversity/issues/10#issuecomment-239165803)

https://groups.google.com/forum/#!topic/openedx-ops/YzTHBlyfX38

**Comment by jagonzalr** [comment]
@renevatium  [PR](https://github.com/proversity-org/edx-organizations/pull/3) created for updating Proversity's [edx-organizations](https://github.com/proversity-org/edx-organizations) staging branch to include update CRUD API operations for users. For now the requirements in base.txt is pointing to [upgrade-edx-organizations-api-users branch](https://github.com/proversity-org/edx-organizations/tree/proversity/upgrade-edx-organizations-api-users).
