### ISSUE TITLE
Anonymous user id mismatch

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#27]
Fix error: "Stored anonymous user id <> for user None in course doesn't match computed id. Seen in production logs.

**Comment by kearabiloe** [comment]
This appears to be a known [Open issue](https://openedx.atlassian.net/browse/TNL-679): changing Django's secret key messes up the anonymous user id table. Still looking for workarounds.

**Comment by renevatium** [comment]
Think this is being caused by to_deprecated_string at [common/djangoapps/student/models.py](https://github.com/edx/edx-platform/blob/master/common/djangoapps/student/models.py):127

**Comment by renevatium** [comment]
Fix is to empty the student_anonymoususerid table. Anonymous IDs get recreated. Will document tomorrow
