### ISSUE TITLE
Fix check for missing year of birth in profile

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#362]
```
    return func(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/djangoapps/util/cache.py", line 85, in wrapper
    return view_func(request, *args, **kwargs)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/views.py", line 618, in course_about
    needs_to_verify_age = not hasattr(request.user, 'profile') or bool(course.minimum_age - request.user.profile.age == 1)
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

**Comment by lidijarad** [comment]
For this error:
- [x] tell user to set age on account page
- [ ] if course has no minimum age set, ensure that the user is not asked to verify that they are zero years or older

**Comment by lidijarad** [comment]
All possible cases that need to be covered:
- [x] if course.minimum_age and user.profile.age are BOTH None
* Tell user to set age
- [x] if course.minimum_age is NOT None and user.profile.age IS None
* Tell user to set age in Account settings
- [x] if course.minimum_age IS None and user.profile.age is NOT None
* Show enroll button
- [x] if course.minimum_age is NOT None and user.profile.age is NOT None
* Show can't enroll, verify age or enroll button depending on age and course min age.

**Comment by lidijarad** [comment]
Merged. Closing.
