### ISSUE TITLE
Investigate ORA Instructor tab

### ISSUE THREAD

**Issue by lidijarad** [proversity-org/edx-platform#387]
Detail how the ORA instructor tab works here.

**Comment by lidijarad** [comment]
[Here](https://github.com/edx/edx-ora2/commit/794f32b18f68be7d5a6ec554ad9904de933834a5) is the specific commit for intruducing the auxillary Instructor Tab view for ORA. [Here](https://github.com/edx/edx-platform/commit/2a1c0217f6681b693542d17d391f0b781486166b) are the changes introduced to edx-platform instructor dashboard.

**Comment by lidijarad** [comment]
Changes needed for edx-platform 
**Tests**
- [ ] lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py >> UPDATE

**Instructor Dashboard**
- [x] lms/djangoapps/instructor/views/instructor_dashboard.py >> UPDATE

**Instructor Dahsboard Javascript files**
- [x] lms/static/js/instructor_dashboard/instructor_dashboard.js >> UPDATE
- [x] lms/static/js/instructor_dashboard/recap.js >>NEW
- [ ] lms/static/js/instructor_dashboard/freetextresponse.js >> NEW

**Instructor Dahsboard Template files**
- [x] lms/templates/instructor/instructor_dashboard_2/instructor_dashboard_2.html >> UPDATE
- [x] lms/templates/instructor/instructor_dashboard_2/recap.html >> NEW
- [ ] lms/templates/instructor/instructor_dashboard_2/freetextresponse.html >> NEW

** Scss/ styling **
- [ ] lms/static/sass/course/instructor/_instructor_2.scss >> UPDATE

Add recap an freetextresponse package data to cms/urls.py and lms/urls.py. Not really sure what this does 
```
JS_INFO_DICT = {
    'domain': 'djangojs',
    # We need to explicitly include external Django apps that are not in LOCALE_PATHS.
    'packages': ('openassessment',),
}
```

* Think about how this recap and freetext should be conbined in 1 JS file and 1 html file.

**Comment by lidijarad** [comment]
MVP for now

- need to create an instructor_dashboard view for recap/freetextresponse
- append section_data to instructor_dashboard.py in lms/djangoapps/instructor
- see if we can pull through xblock data to the new Recap Tab in the instructor dashoard view. The logic for getting the freetextresponse answers is already available?

**Comment by lidijarad** [comment]
@renevatium, do you know what this piece of code in lms/urls.py is supposed to do? I'm wondering if I have to include this for the recap instructor dashboard view?

```
JS_INFO_DICT = {
    'domain': 'djangojs',
    # We need to explicitly include external Django apps that are not in LOCALE_PATHS.
    'packages': ('openassessment',),
}
```

**Comment by renevatium** [comment]
@lidijarad I'm not entirely sure what that accomplishes but at first glance I'd say that it has to do with JS compilation considering that djangojs is one of the translation block identifiers. We'll look into it tomorrow.
