### ISSUE TITLE
add DELETE endpoint to microsite API

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#394]
@lidijarad can you please add a DELETE endpoint to the microsite API to delete a previously created microsite along with its site and ORG. 

@renevatium also mentioned something about course modes, Rene can you elaborate a little, please?

*don`t forget to test :) *
Thanks

**Comment by renevatium** [comment]
@lidijarad don't worry about modes for now. That's more of an issue with course creation and currency.

**Comment by lidijarad** [comment]
@nicovanniekerk  @renevatium, when would you like this endpoint added by? I think it will be relatively quick to add the DELETE endpoint but a little more time for the tests. I would just like to set aside time to work on this while I work on the BoE features for instructor dashboard. Due date?
