### ISSUE TITLE
Implement  Certificate generation on passing grade == True 

### ISSUE THREAD

**Issue by lidijarad** [proversity-org/edx-platform#416]
For a verified course with an end date, I want to know if the certificate is generated/issued on the end date, or as you complete the course (which might be a few days before the end date.)

**Comment by lidijarad** [comment]
@jagonzalr ```For courses that are run on a specific schedule – for example, a college that runs an edX course during the Spring semester – the criteria for getting a certificate are pretty unambiguous: when the semester is over (and the course end date has arrived), you need to have a passing grade for the overall course. If these two conditions are met (course end date has arrived, and you have a passing grade) then on your Student Progress page you will see the option to “View Certificate”.```
Both conditions need to be satified. See code here: ``` lms/djangoapps/certificates/queue.py```

**Comment by nicovanniekerk** [comment]
this all works faaanks
