### ISSUE TITLE
Scientific equation gives error when submitting answer

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#454]
When the user submits his answer he gets an error message.

Steps to reproduce:
1. Click the link below - The scientific equation should display:
http://staging.studio.proversity.io/container/block-v1:edX+SC101+2017+type@vertical+block@15051345624d46d2aa64e51243936ade
2. Click 'Show answer'
3. Copy and paste the answer into the answer section and select 'Submit'

Results:
The user gets an error message - See below screenshot

Expected Results:
The user is able to submit his answer without getting the error message

![image](https://user-images.githubusercontent.com/31007393/30163374-099e32fc-93d9-11e7-9853-20dae475b64f.png)

**Comment by nicovanniekerk** [comment]
we dont use this stuff, so if it becomes a problem we will fix it but for now. noope.
