### ISSUE TITLE
User does not get confirmation when unrolling from a course

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#460]
When a user unenroll from a course, nothing happens. 

Steps to reproduce:

https://learn.teachfirst.org.uk

1. Click on the link above and login.
2.  Click non Explore Courses - all the courses should be listed
3. Select a course.
4. The course 'About page' will display, enroll in the course
5. The courses of the user will be displayed.
6. Click on the 'Gear' of the course just enrolled.
7. Select Uninroll
8. In the new popup window, select Uninroll

Results:
The popup window in step 8 keeps displaying and the user does not get informed that he/she has successfully unrolled from the course and the page does not refresh to show course has been removed form the user enrolled courses. 

Expected results:
The user should get prompted/message that he successfully unenrolled of the course and when clicking OK on the popup message, the page should refresh and the page updated with the  course removed.

**Comment by nicovanniekerk** [comment]
@mariushuman please recheck this on a couple of the sites, i believe we fixed it

**Comment by mariushuman** [comment]
@nicovanniekerk this was tested. I went through a couple of microsites just to confirm and all looks good.
