### ISSUE TITLE
User get prompted about refund when unenrolling

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#462]
When the user is unenrolling from a course on Udify, he gets an error message: 
Unable to determine whether we should give you a refund because of System Error. Please try again later.

http://staging.udify.proversity.io/

1. Click on the link above
2. Enroll in a course
3. Select the hamburger menu and select 'Dashboard' - The enrolled courses will display
4. Select 'Option' and and select unenroll.

Expected results,
The user is able to unenroll.

Results:
The user gets an error message.

Error Message:
![image](https://user-images.githubusercontent.com/31007393/30531491-f9a725f6-9c4e-11e7-8307-15f9e1ab26e4.png)

**Comment by mariushuman** [comment]
@nicovanniekerk , this is also happening on BSG
![image](https://user-images.githubusercontent.com/31007393/30534127-0a6959dc-9c5d-11e7-894a-afcf26f072fb.png)

**Comment by nicovanniekerk** [comment]
Massive changes are present in the html templates  that is bound to this functionality.
@bronsondunbar will compare the changes and apply it to udify for testing.

@renevatium @mariushuman FYI

**Comment by bronsondunbar** [comment]
This has been fixed. @nicovanniekerk @renevatium @mariushuman
