### ISSUE TITLE
Unit 'Preview' not working on studio.proversity - awaiting upgrade

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#467]
When a user wants to 'Preview' a unit, he gets a 'Page could not be loaded' and an error in the dev console.

https://studio.proversity.org/

1. Click on the link above and login.
2. Select a course  - NOTE: the courses is live and changes should net published or saved!
* I have used the Testing Testing and Tea006 courses to confirm 
3. Select section, sub-section and select a unit
4. When in the unit, click the 'Preview' tab

Results:
The user gets a 'Page could not display' and an error message in the dev console
![image](https://user-images.githubusercontent.com/31007393/30634897-f005bfc8-9df0-11e7-8804-835ed66d61f6.png)

Expected Restuls:
The user is able preview the unit.

**Comment by nicovanniekerk** [comment]
@mariushuman found issue, is being fixed on staging, will fix production tonight

**Comment by mariushuman** [comment]
@nicovanniekerk is this fixed? I get the following screen saying that I need to check my firewall:
![image](https://user-images.githubusercontent.com/31007393/37819078-f6516ca4-2e84-11e8-90b4-f9db971c8925.png)

**Comment by nicovanniekerk** [comment]
@mariushuman its fixed on staging,  production will be done after hours as it requires a nginx config to work securely and i can only test that when prod not so busy.

cc @renevatium

**Comment by mariushuman** [comment]
@nicovanniekerk are you going to push this with the upgrades to production next week Tuesday?

**Comment by nicovanniekerk** [comment]
preview has been fixed and running on preview.proversity.org

**Comment by mariushuman** [comment]
@nicovanniekerk great, it is now working in production. I will close the ticket.
