### ISSUE TITLE
Investigate and add Enrollment API endpoint

### ISSUE THREAD

**Issue by lidijarad** [proversity-org/edx-platform#480]
Enrollment API needs an endpoint (if not already possible), that allows for a learner to be enrolled in multiple courses in one call.

**Comment by jagonzalr** [comment]
We already have [this](https://github.com/edx/edx-platform/pull/15006)

Tested already on staging and works.

**Comment by lidijarad** [comment]
@jagonzalr, cool. Moving this issue to done and closing it.
