### ISSUE TITLE
Add course clear API endpoint

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#499]
The course cache can be cleared by running the following commands on the platform server,
we can, however, add this as an api endpoint to do this for us. :P)

```
$ python manage.py lms shell --settings=aws
> from openedx.core.djangoapps.content.block_structure.api import clear_course_from_cache
> from opaque_keys.edx.keys import CourseKey
> course_key = CourseKey.from_string('course-v1:edX+DemoX+Demo_Course')
> clear_course_from_cache(course_key)
```

@jagonzalr or @lidijarad which one of you will do this first, hehehe. no rush just something to help us out in the long run.

@renevatium FYI

**Comment by mariushuman** [comment]
Documented on 'Useful Commands' WIKI.
