### ISSUE TITLE
Filter staff from reports

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#52]
Filter staff out of reports.

**Comment by dominicfollett** [comment]
Leaving out:
1. Download a CSV of learners who can enroll. This option only finds learners who have been invited via email only, and may include staff members which is useful information.
2. View certificates issues (& its related download csv option). It contains no user information.

**Comment by dominicfollett** [comment]
@renevatium I've submitted a pull request Sir for when you are free :)
