### ISSUE TITLE
Add support for Org logo download for microsites API

### ISSUE THREAD

**Issue by lidijarad** [proversity-org/edx-platform#521]
Consola will now send logo url in payload, need to download remote image, and save the logo to the Org model.

**Comment by nicovanniekerk** [comment]
pull request = https://github.com/proversity-org/edx-platform/pull/538

**Comment by nicovanniekerk** [comment]
pull request merged, deployment in progress

**Comment by lidijarad** [comment]
This has been deployed. Closing issue.
