### ISSUE TITLE
research into certificate generation

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#525]
certificates, for some reason, gets shown when you complete the course but then goes  bye bye.
we need to either make a lekker enhancement to platform, for this to just work like it should, or we need to make an automatron to do this for us.

**Comment by mariushuman** [comment]
@nicovanniekerk ,can we close this ticket? Not sure if an enhancement was made or if you build your automatron thingy to resolve the issue?

**Comment by nicovanniekerk** [comment]
@mariushuman i think it just happened to start working correctly with a upgrade. closing.
