### ISSUE TITLE
confirmation of Terms of Services and Honor Code not working

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#528]
When a user attempts to register, he gets an error message that says-
'THE FOLLOWING ERRORS OCCURRED WHILE PROCESSING YOUR REGISTRATION:
You must accept the terms of service.' Although it is selected.

ulr: any Microsite - https://learn.teachfirst.org.uk/

Steps:
1.  Click on the above url
2.  Click on Register.
3. Complete the form and make sure that the Honor code IS ticked.

Results:
The user gets an error message. See below
![image](https://user-images.githubusercontent.com/31007393/32208852-d7f3e062-be0d-11e7-8a0b-71b2e98ba7f8.png)

Expected Results:
The user should be bale to register on the site.

**Comment by nicovanniekerk** [comment]
@mariushuman turning on the combined registration flag does not render in the same error.
Spoken to @jagonzalr and we going to wait for rene, to come in tomorrow so we can talk about turning this on for all microsites.

**Comment by mariushuman** [comment]
@nicovanniekerk can you please update TF so the ToS and Honor code is combined again?

**Comment by nicovanniekerk** [comment]
@mariushuman gonbines login registration has been activated, and TOs has been set to hidden. please check you can register a dumy user.

**Comment by mariushuman** [comment]
@nicovanniekerk Thanks, created a dummy user and no issue with the combined ToS and Honor code.
Will close the ticket
