### ISSUE TITLE
Prefer order by course enrollments in dashboard

### ISSUE THREAD

**Issue by jagonzalr** [proversity-org/edx-platform#531]
By default course enrollments in dashboard render from last created to first created.

The idea is to use the already in production flag ```USER_COURSE_ENROLLMENTS_ORDER_BY``` to order by the course enrollments.

[PR to development](https://github.com/proversity-org/edx-platform/pull/533)
[PR to staging](https://github.com/proversity-org/edx-platform/pull/532)
[PR to production](https://github.com/proversity-org/edx-platform/pull/534)

**Comment by nicovanniekerk** [comment]
Development updated and tested.
Staging updated and tested.
Production merged and will be updated tonight.

**Comment by nicovanniekerk** [comment]
Release note:
This allows to order  the user dashboard in the following ways:
1. a-z
2. z-a
3. first created to last created
4. last created to first created

**Comment by mariushuman** [comment]
This works in the backend as per Nico Comments
