### ISSUE TITLE
Tab text colour is set to white, so user cannot see it

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#537]
With certain problem types (Questions) the tab text is the same colour as the background. This is causing confusion when the LD team set up their questions as they cannot see the tab text on LMS

url: all microsites

Steps:
When a user view the question, the tab Save and Resettab seems not to be active, although the tab is active but the text colour is also white. 

Please see the setup on Studio where the tabs are setup:
![image](https://user-images.githubusercontent.com/31007393/32329544-124e32d8-bfe6-11e7-8b0f-475c194eed18.png)

tabs missing:
![image](https://user-images.githubusercontent.com/31007393/32328743-95822126-bfe3-11e7-8683-5eac9bb05086.png)

Tabs highlighted:
![image](https://user-images.githubusercontent.com/31007393/32328906-14beb800-bfe4-11e7-84dd-850c67ecd9fd.png)

@nicovanniekerk FYI

**Comment by mariushuman** [comment]
@bronsondunbar Can you have a look at this when you have 2 minutes:

ur: https://pfn.proversity.org/
Module 2
The Structure of the Financial System
Unit 2: Activity 1 — Check for Understanding

At the bottom of the page, you should see tabs Save | Reset | Show Answer
The text are white so it is not visible for selection.

**Comment by nicovanniekerk** [comment]
@mariushuman @bronsondunbar please note that these buttons are dictated from studio, choops, check the course and make sure it is configured correctly around these buttons.

**Comment by bronsondunbar** [comment]
@mariushuman Fix has been added and tested on staging. It was a CSS issue.

http://staging.pfn.proversity.io/

cc: @nicovanniekerk

**Comment by mariushuman** [comment]
This is resolved and can be closed.
