### ISSUE TITLE
User cannot save Free Text Response problems

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#539]
When a user user click on 'Save' and moves away from the page, for instance, reviewing videos or other course information, the user text is lost and has to re-do it.

URL: https://learn.teachfirst.org.uk/courses/course-v1:TEA+TEA010+2017/courseware/fd419e184e3c414a9a45162883fd7bc5/a8cd53e294cb405eb3b3fb8cf2fdc182/?activate_block_id=block-v1%3ATEA%2BTEA010%2B2017%2Btype%40sequential%2Bblock%40a8cd53e294cb405eb3b3fb8cf2fdc182

Steps: 
1.  Click on the link above
2.  Scroll to the answer block and enter text 
3.  Click 'Save' - The user get a message:  "Your answers have been saved but not graded. Click "Submit" to grade them.
4.  Click on Next, Back or click on any of the navigation tabs at the top of the course
5.  Go back to you original page where you saved your text

Results.
The text enter and saved is not visible.

Expected Result:
The user is able to save his text and come back to review/edit/modify it.

**Comment by nicovanniekerk** [comment]
@lidijarad this is in the freetext xblock itself, can you please have a look at this. 

@mariushuman please retest this and when you are back on the page with the question and is supposed to see your text, inspect the element and see if the text is not just hidden from view.

**Comment by lidijarad** [comment]
@nicovanniekerk, I have looked into this. The content appears if the page is reloaded, but when using the previous and next buttons to navigate within a section, it doesn't show the saved content. I will investigate further. We might have to force reload the page when clicking on save.

**Comment by nicovanniekerk** [comment]
@lidijarad perhaps, that little save button, can just on click also save that fields data in local storage and then on page load just check local storage and bring the value back. i suspect that value is pulled over an api with js which is only called on initial page load, i.e. the actual loading of the page, but when you use the arrows to navigate the page does not reload conpletely but still does, its a wierd little browser thing, however the arrow come back to page refresh, does recheck local storage, thats why it does it, in part. so maybe this can actually be a quick win using local storage.

**Comment by lidijarad** [comment]
@nicovanniekerk, ok thank you for the suggestion, maybe that's an option, let's think about the pros and cons. Also, do we know how this behaves on the apps?

**Comment by lidijarad** [comment]
I have created a new issue for this in the correct repo, https://github.com/proversity-org/xblock-free-text-response/issues/12

**Comment by lidijarad** [comment]
I think this has been deployed to staging? See issue above. @nicovanniekerk @mariushuman

**Comment by nicovanniekerk** [comment]
@lidijarad @mariushuman this is on staging and is working lekker!!

i am going to put this on production tonight.

**Comment by nicovanniekerk** [comment]
This has been done and deployed, answers save now.
