### ISSUE TITLE
Hide Course Home Sidebar advanced setting

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#54]
Option/feature to hide handouts on course info pages

**Comment by renevatium** [comment]
Will need to be added as an Advanced Setting as is just an html block

**Comment by dominicfollett** [comment]
Something to note, the name for Course Home Sidebar is not changed in studio 'updates' view, which would confuse an instructor who set that up in advanced settings.

**Comment by renevatium** [comment]
Really? Wow, just another example of bad UX from EdX. Maybe update that as a separate task

**Comment by dominicfollett** [comment]
Catch empty string, slightly grey out. On disabled view, make name equal to saved name if any otherwise default.
