### ISSUE TITLE
Load courseware to first module/unit/component

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#56]
Course tab link loads via redirect from /courseware but lands on an empty page. Rather redirect to first unit.

**Comment by dominicfollett** [comment]
@renevatium the empty page is supposed to house an entrance exam. There is also 

``` html
${fragment.body_html()}
```

sitting at the bottom of the div. What I could do is  if an entrance exam is not defined, then redirect to the first course unit?
