### ISSUE TITLE
Bulk register enroll API

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#560]
William from harambee is in the process of coding his integrations. and during this he has identified some small issues.

- [x] when the API is called with the following example body
`{
    "auto_enroll": true,
    "action": "enroll",
    "courses": "course-v1:HAR+b2e1ecbb-be18-48cf-b8c7-fc412a917395+infinite, course-v1:HAR+BC_101+2017_01",
    "email_students": false,
    "identifiers":"user1, user2",
    "country": "South Africa",
    "course_mode": "audit",
    "email_extension": "@harambeecloud.com"
}`
the identifiers in this json is user1 and usser2, and the email extention is @harambeecloud.com
now the api will try to register user1@harambeecloud.com as email and username of user1, if this user1 exists in the system as a username, although the emails is not the same, this user will not be registered again as the username is taken, the api does not return anything on this usse case, i.e. it will try and enroll user1@harambeecloud.com, but the user does not exist and it could not create the user because the username is taken. in cases where the username is already taken but the emails differ, the api will have to return a message, such as "user1 could not be created with {email extention} because it has email {actual email}" i.e. return a username already exits with this email address message to allow the client side to know why the user was not enrolled.

- [x] in the same json, the list of courses are comma seperated, but the second item has a space just before the course id, the api takes this space as part of the course id, it should just to a strip to clear out all the white space arounf the id.

@renevatium @jagonzalr priority kinda high :)

**Comment by lidijarad** [comment]
@renevatium @nicovanniekerk, there is also an issue with this, if ancourse_key that doesn't exist is passed to the `students_update_enrollment` function in (instructor api.py) it doesn't catch the error, it just returns a 404.

**Comment by nicovanniekerk** [comment]
Merged to deployment. awaiting grades api and SSO

**Comment by nicovanniekerk** [comment]
Tested and all goood.
