### ISSUE TITLE
grades API

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#565]
The grades api is only using usernames to pull the grades for the course. we need to make this work the same way as the bulk enroll api, by using the emiail_extention in the body of the request and then filtering the user request to the database also with username or email. 

i.e. please add email extention to the request and enhance database filtering to check username || email.

**Comment by lidijarad** [comment]
@nicovanniekerk, noted. Will make this part of the fixes/updates I'm working on.

**Comment by nicovanniekerk** [comment]
updates merged and tested on development, looking good
