### ISSUE TITLE
Video transcripts not working together for two video urls in same video

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#568]
When a video is loaded in STUDIO with a transcript and a second video (for download purposes) is loaded the original transcript gets overwritten by the auto transcript from MVP. 

url: http://staging.studio.proversity.io
Create a new course or use the below one to replicate the issue:
Course: November 2017 Release
Section:  KHDA Transcripts  

Steps
1.  Click on the link above and login
2.  Create a course or go the course mentioned above
3.  Create a new video unit.
4.  Login To MVP to copy a video url.
5.  On Edit on the Video unit and add the video URL.
6.  Add a transcript.
*  All is working fine
7.  Click on Add URL and add a second url from the mvp from the same video (720p video)
8.  The Video is loaded without a transcript
9.  Add a transcript
* The transcript is added without any issue
* The unit can be published and the video should play.

10. Add a second video unit.
11. Go to MVP and copy a second video url
12. Go to the new video unit and add the video url.
13. Load a transcript
*Transcript is loaded without issues.
14 Go back to MV and copy the 2nd url (720p video)
15. In STUDIO, click on Add URL and add a second url from the mvp from the same video (720p video)

Results
The video is added and it auto loads the previous transcript form the previous video that was loaded.

Expected results
1.  When the second video url is loaded, it should not load a transcript. It should keep the original
     transcript that was loaded by the designer. 
2.  Also, when the designer click save and goes back into the video unit, their is a warning/error message
     saying that the transcript does not match and that the correct one should get selected. Even when
     the correct one is selected and saved, when the designer goes back in again, it prompt the same
     question.

**Comment by mariushuman** [comment]
@jagonzalr Can you have a look at this ticket today if you don't have any major stuff to look at - Thanks!?

**Comment by jagonzalr** [comment]
@mariushuman @nicovanniekerk I made a change on MVP, it will involve changing the mp4 urls on Studio, eg: change ```https://exports.proversity.org/KHD/KHD001/KHD001_AppNav/video-720p.mp4``` to this ```https://exports.proversity.org/KHD/KHD001/KHD001_AppNav.mp4``` after re-transcoding the video on MVP

**Comment by jagonzalr** [comment]
@mariushuman @nicovanniekerk I made a change on MVP, it will involve changing the mp4 urls on Studio, eg: change ```https://exports.proversity.org/KHD/KHD001/KHD001_AppNav/video-720p.mp4``` to this ```https://exports.proversity.org/KHD/KHD001/KHD001_AppNav.mp4``` after

**Comment by mariushuman** [comment]
@jagonzalr Was it because the actual .mp4 video was not in same folder (/KHD001) as the m3u8 video?
I'm just asking as Pata didn't had this issue, and it was only this one video on KHDA that had this extra folder?

**Comment by jagonzalr** [comment]
@mariushuman the issue is how edX stores the name of the transcript, it always grabs the item of the list of videos, so if the last item is the mp4 it was always gonna be video-720, now I change it to always be unique. We should actually check PATA and see that the transcripts are correct because at the beginning they didn't add the mp4 url but later they did.

**Comment by mariushuman** [comment]
@jagonzalr thanks for clarifying that. I already checked and all is good on PATA.

**Comment by nicovanniekerk** [comment]
@mariushuman please close this ticket if the transcript is now sorted, thanks

**Comment by mariushuman** [comment]
Checked Pata yesterday and just checked KHDA, all good.
