### ISSUE TITLE
Abbreviations display in export documents - awaiting upgrade

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#575]
When a course administrator exports the the lists of learners enrolled in a course, the field 'Level_of_education' only show abbreviations and not the full description. This abbreviations is not sufficient for when course admins as it is vague and does not mean anything.

url: https://pata.proversity.org

Steps:
1.  Click on the url above and login
2.  Select a course 
3.  Click on the Instructor tab
4.  Click on DataDoenload
5.  Scroll down to Reports and select the option - Download profile information as a csv
6.  Scroll all the way down and download the export list and view the level of education column

Results:
When the list is opened and the column 'Level_of_education' is viewed, the abbreviation of the each level is displayed that have no meaning.
See screenshot below

Expected results:
When the column is viewed, the full names of each education level should display.

![image](https://user-images.githubusercontent.com/31007393/33168462-a1d6d176-d049-11e7-837d-62d876ee00a7.png)

**Comment by nicovanniekerk** [comment]
@mariushuman i have found the issue and have placed a fix for this on development.learn, you can go check it there quick. however, seeing as the new updates are almost ready to be rolled out, please check with andrea if she can wait a little longer for this, but if it is a "I NEEDS IT NOW" thing, i can squeeze it into production, b ut would prefer to hold until it has been super tested with the new upgrades.

**Comment by nicovanniekerk** [comment]
this has been fixed and deployed, closing
