### ISSUE TITLE
CITB Welsh translation update

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#579]
Emma has found some Welsh translations that are missing from the Welsh language set and it needs to be updated, strings and translations can be found here.

https://docs.google.com/a/proversity.org/spreadsheets/d/1rPDmFH_4-_asrGOcAoBbRMUEpEEDlUitWgwYFgptnaY/edit?usp=sharing

@jagonzalr I am assigning it to you, but if you do not have capacity pas it on.
Needed within the +- 10 days.

@mariushuman @renevatium FYI

**Comment by mariushuman** [comment]
@nicovanniekerk @jagonzalr - I have added some missing Welsh translations. See the tabs in the spreadsheet for them. 

When viewing the course, it looks like the Bookmark this page gets reverted back to English, as the name flash when the page is loaded. Looks like that mechanism is a bit broken. 
Forgot, I also created a ticket (https://github.com/proversity-org/edx-theme-microsites/issues/264) as the url link in the email to reset you password is incorrect.

**Comment by nicovanniekerk** [comment]
@mariushuman spoke to @renevatium and he is going to take the translations on this.

**Comment by mariushuman** [comment]
@nicovanniekerk Ok, cool. @renevatium if you need anything let me know.

**Comment by nicovanniekerk** [comment]
@mariushuman you aware of anything here still outstanding?

**Comment by mariushuman** [comment]
@nicovanniekerk, Rene completed the translations for Platform, but not yet for mobile, assume that will be for Android.

**Comment by nicovanniekerk** [comment]
@mariushuman i believe there are still some translations missing for this? please confirm and if not close this. fanks
