### ISSUE TITLE
Instructor Annotations

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-platform#58]
Investigate URL for Annotation Storage advanced setting.

**Comment by renevatium** [comment]
Setting is for [CATCH](https://osc.hul.harvard.edu/liblab/proj/catch) data store for [instructor annotations](http://www.equtek.com/clients/edX/annotation_beta/setup.php)

**Comment by nicovanniekerk** [comment]
annotations is now on the notes service and it does work it the course is setup correctly, also EDX now has a review function that we do need to activate sometime.
