### ISSUE TITLE
Text miss align 

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#580]
Selection box and text are miss aligned. 

url: http://staging.learn.proversity.io
Course: PRO: QA_002 NOVEMBER 2017 - /course-v1:PRO+QA_002+2017

Steps:
1.  Click on the link above and login
2.  Select the course above  or  any other course
3.  Click on the Instructors tab and select the Certificates tab.
4.  Scroll down until you find Bulk Excepstions.

Results:
The Browse tab and test are miss aligned - See screen shot below:
![image](https://user-images.githubusercontent.com/31007393/33266324-d1860554-d37d-11e7-8c96-7e1bcf3b6d6c.png)

Expected results:
The tab and text should all be aligned.

**Comment by nicovanniekerk** [comment]
@bronsondunbar @mariushuman i fixed this by making the border and background of the button transparent. it now just looks normal. i wil lmake the fix to production and run the update tonight sommer.

**Comment by mariushuman** [comment]
@nicovanniekerk I can see the changes on Staging but not yet in Production. Let me know when that changes are made in production? Thanks

**Comment by mariushuman** [comment]
@bronsondunbar , can you please check this on a mirosites?
use https://khda.proversity.org

Follow the steps above.

* The current 'Browse' button does not open a browse window.
* If you move your mouse to the top right hand side of the box, the mouse cursor change to a selector, if you then click a browser window opens up.
![image.png](https://images.zenhubusercontent.com/5991a3008f62dc7798c2ae6e/cd4d20fc-280c-447e-a745-e4aec811bf27)

**Comment by nicovanniekerk** [comment]
@mariushuman Fanks, please check if the one on learn is fine. @bronsondunbar this is not somthing people use that often, so feel free to wait untill you have a couple of stuffies to fix and do them together, just little better time saving :)
