### ISSUE TITLE
Text & Icon not displaying in unit course bar

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#586]
When the learner is in the course, he cannot see the the previous or next units as the they are blank.

url: https://learn.harambeecloud.com/courses/course-v1:HAR+BC_101+2017_01

Steps:
1.  Click on the link above and login
2.  Select the course TEST_ Choppies braai course
3.  Select Course and select the first module 'Charcoal'
4.  The unit is loaded with the different unit listed above

Results.
Only the current unit that is viewed is visible on the bar.
![image](https://user-images.githubusercontent.com/31007393/33418492-cf36baea-d5ae-11e7-943b-f1228aa72d0d.png)

Expected Results:
All units should be visible.

**Comment by nicovanniekerk** [comment]
@bronsondunbar let me know when you has the fix :)

**Comment by bronsondunbar** [comment]
@nicovanniekerk I have pushed a CSS update, will need to test on staging to see if it works. cc: @mariushuman

**Comment by mariushuman** [comment]
@bronsondunbar it looks good on staging...

**Comment by mariushuman** [comment]
@nicovanniekerk I have tested this on https://learnuat.harambeecloud.com/ and it looks like the unit tabs are now displaying.

Can we close the ticket or should we keep it open until we can test it on their prod server?

CC: @bronsondunbar

**Comment by nicovanniekerk** [comment]
@mariushuman lets get it on prod first.
