### ISSUE TITLE
Certificate print

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#592]
When completing a course and a user is presented with their certificate, the user gets an option to print the certificate, when the user clicks to print the certificate the print preview and the actual print, will pull in the footer links as text in the printed version of the certificate, this should not happen, either the footer needs to build the exact links it needs to navigate to each of the links.

See attached screenshot as an example. but since the certificate is generated with html, i think we can just remove the footer completely from the certificate html.

![certificate print preview](https://user-images.githubusercontent.com/3447257/33544415-53ff9882-d8e3-11e7-97b7-5303289ccd6c.PNG)

[KHD KHD001 Certificate _ LearnApp by KHDA.pdf](https://github.com/proversity-org/edx-platform/files/1526341/KHD.KHD001.Certificate._.LearnApp.by.KHDA.pdf)

@mariushuman FYI, please follow this and get it in ASAP.
@bronsondunbar @jagonzalr please liase between you too and get this sorted as soon as you can please, clients will be starting to pull their own certificates real soon and this looks bad.

@renevatium FYI

**Comment by mariushuman** [comment]
We already have a ticket for this:
https://github.com/proversity-org/edx-theme-microsites/issues/257
