### ISSUE TITLE
Additional text displays in course card wrt certificate - awaiting upgrade

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#608]
When a user logs in and view the course card on the dashboard, their is additional text:Final course details 'are being wrapped up at this time. Your final standing will be available shortly.'
This appears even before the learner has started the course.
According the 

url: https://pata.proversity.org

Steps
1.  Click on the link above and login
2.  View the course card

Results:
The additional text displays.
According to edX docs, this text will only display when there is an 'End Date' set for the course. For Pata there is no End Date set. see section 9.3
http://edx.readthedocs.io/projects/open-edx-learner-guide/en/named-release-cypress/SFD_certificates.html 

Expected results
The text should not display

**Comment by mariushuman** [comment]
@nicovanniekerk forgot to mention that when you hover over the text, the mouse cursor change to a 'finger pointing hand'

**Comment by nicovanniekerk** [comment]
@mariushuman @bronsondunbar this finger pointing thingy is purely css and html. 
with the text being displayed it is either invalid switches in the html, or the python sending in the information is incorrect.

@bronsondunbar can you please deal with the hand thingy, i will look into the text display thing.

**Comment by bronsondunbar** [comment]
@nicovanniekerk I have updated the master template and removed the cursor pointer. This will only be displayed if the element is a link. cc: @mariushuman

**Comment by mariushuman** [comment]
This is sorted, The text does does not appear any more (check ticket 657) of why this happened.
Also, when you hover over the certificate link, it is now a link that is selectable.  Ticket will be closed.
