### ISSUE TITLE
Investigate archiving courses and how it can be linked to user state

### ISSUE THREAD

**Issue by lidijarad** [proversity-org/edx-platform#621]

**Comment by nicovanniekerk** [comment]
@lidijarad i did create a ticket for this on friday, but its ok, ill close that one and we can use this one, please update progress as you go along and let me know on here when you ready to test and so on :)

https://github.com/proversity-org/edx-platform/issues/618 just as reference,

**Comment by nicovanniekerk** [comment]
this has been completed and archived courses are now called "past courses"
