### ISSUE TITLE
Missing Welsh translations

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#625]
Update Welsh translations for CITB, missing strings can be found [here](https://docs.google.com/document/d/1YDXVCgqUZtXTK5eey4st0y4jkQvSRNelrVoKXsPYpAg/edit?usp=sharing).

@mariushuman can you please compile the Welch side of the strings, maybe Andrea knows of someone that can do the translation quick. and once you have the strings, please pass it on to @lidijarad to please add and compile them quick.

**Comment by mariushuman** [comment]
@nicovanniekerk I filled in the missing Welsh translations. I have asked Andrea to forward it to the guys who did the welsh translations to confirm that we don't loose the meaning. As soon as I have feedback I will let you know.

**Comment by nicovanniekerk** [comment]
@mariushuman second welsh translation ticket i am seeing. please close one of the two.

**Comment by lidijarad** [comment]
@nicovanniekerk , @mariushuman  has this been resolved?

**Comment by nicovanniekerk** [comment]
yes, close

**Comment by lidijarad** [comment]
This can be closed.
