### ISSUE TITLE
Course preview Video (About Page) keeps playing when you close it

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#654]
When you play the video on the about page, and close it using the 'x' button in the top right hand corner, the video still keeps playing.

url: All microsites (Staging & Prouction)
https://khda.proversity.org/

Steps

1.  Click on the link above (Do not sign in)
2.  Select a course
3.  Play the video.
4.  After the video has started playing close the video

Results:
The video keeps playing, even though you have closed it.

Expected Results
The video should stop playing.

**Comment by mariushuman** [comment]
@jagonzalr can you look at this, if it is going to take to longer then 10 min to resolve just pass it on to @nicovanniekerk or @lidijarad so they can look at it when they have the capacity to do it?

**Comment by lidijarad** [comment]
@bronsondunbar, I'm handing this over to you as you are already familiar with the code for the video playback. I have identified that the code lives in 
`edx-theme-microsites/KHD/static/js/app.js`

This function should stop the video from playing when the iframe is closed:
`$(".watch-video-close-btn").click(function(e) { switch (e.preventDefault(), $(window).width()) {`

**Comment by lidijarad** [comment]
Here is a link to test 
https://khda.proversity.org/courses/course-v1:KHD+KHD001+2017/about

**Comment by bronsondunbar** [comment]
@mariushuman This has been fixed on staging

**Comment by mariushuman** [comment]
@bronsondunbar Great thanks. You can push to production.
