### ISSUE TITLE
Incorrect certificate message appear underneath course image

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#657]
When a user gets enrolled, a message appear underneath the course card image:
'Final course details are being wrapped up at this time. Your final standing will be available shortly.'
This is icorrect and should display something else or nothing

url: https://advance.cause4.co.uk/
Pre-request - A user must be enrolled in a course with a certificate.

Steps:
1.  Click on the url above and login
2.  Select the Hamburger menu and select Dashboard.

Results:
The user gets a message:
'Final course details are being wrapped up at this time. Your final standing will be available shortly.'

Expected Results:
The user should get a different message or no message at all.
![image](https://user-images.githubusercontent.com/31007393/36306274-bcd0ad62-131f-11e8-911d-c1547f2e154c.png)

**Comment by nicovanniekerk** [comment]
Fix pushed to staging, found that the certificates does not handle the unavailable status, and the default status on the certificate is set to "processing", which in the theme files means show this message.

I changed the default status to be "unavailable" like it should be, and then added it to the theme files. it will now say you need to finish the course to get a certificate

**Comment by nicovanniekerk** [comment]
@mariushuman can you please confirm this is fixed and close this. fanks

**Comment by mariushuman** [comment]
This is fixed, ticket can be closed.
