### ISSUE TITLE
Ghost lines appear at the bottom of course pages

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/edx-platform#662]
When a user goes through the course, at the bottom of the page random, lines appear.

url: https://khda.proversity.org/
**All microsites

Steps:
1.  Click on the link above and login
2.  Select a course.
3.  Click on the course tab
4.  Scroll through the different units
**Check this specific unit:
![image](https://user-images.githubusercontent.com/31007393/36717304-389d5df8-1ba6-11e8-8e8e-89c66ddd4e75.png)

Results:
There should be no lines at the end of page

Expected Results:
Random ghost lines appears at the bottom of the page.
![image](https://user-images.githubusercontent.com/31007393/36717263-11f54ed6-1ba6-11e8-8b43-9d0eaef88897.png)

**Comment by nicovanniekerk** [comment]
ps: this happens on all sites and all courses if you have more than on module in your section. Tonio i did a little digging into this last week, and found that the course unit list, contains all units hierarchically downwards. example if you have 2 modules,  module 1 will be added to the html structure, and then module 2 will be added into module 1 an a child of module 1 and not as a child of the structure.

**Comment by jagonzalr** [comment]
I copy this part of KHDA course in my local studio https://khda.proversity.org/courses/course-v1:KHD+KHD001+2017/courseware/2a89da70c9404ccb845f732fb303f58f/7ef1df75a0474096ab9a72e2b091c871/?activate_block_id=block-v1%3AKHD%2BKHD001%2B2017%2Btype%40sequential%2Bblock%407ef1df75a0474096ab9a72e2b091c871 and run it on devstack and the lines are not appearing.

**Comment by nicovanniekerk** [comment]
@jagonzalr @maruis_human i found this issue and the fix is building on staging.

**Comment by mariushuman** [comment]
The issue is resolved and is in production. Ticket can be closed
