### ISSUE TITLE
Initial GDPR enhancement

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/edx-platform#728]
With GDPR becoming more and more important we need to remove the data download that is available on the instructor page, specific the the profile information. 

The below image shows the button that must be removed to not allow anyone to download the profile report.

Implementation:

Please protect this button "html section" in the html template files with a setting, the microsite_configuration django app caters for microsite and main site configurations, please add this setting as "ALLOW_PROFILE_DOWNLOAD" and protect the django template file.

As an example follow the code that uses the setting "show_global_message".

Notes: this will be an update to the following repos:
edx-platform => to edit the template file to protect the download section with the new setting
configuration => to apply the setting to the lms.env.json file
edx-deployment => add the setting to the server-vars.yml file.

![image.png](https://images.zenhubusercontent.com/58b67c4151aa2c3057771994/6ac40909-7bb9-4c7b-961f-61f70ea30302)

@jfavellar90 Please see this as high priority and would be great if it can be started next week.
@mariushuman @renevatium FYI

**Comment by nicovanniekerk** [comment]
@jfavellar90 Please can we get on this issue ASAP, we need this in production within the next two weeks, EU is going live with their new GDPR policies at the end of this month and we will get massive fines if this is not in place.

**Comment by jfavellar90** [comment]
@nicovanniekerk I don't think we need to do a change on configuration repo. We can use the variable EDXAPP_ENV_EXTRA on deployment server-vars file to add our new env setting. What do you think about it?

**Comment by nicovanniekerk** [comment]
@jfavellar90 Thanks for the Pr I merged to development and test it, and its all good, merged it to master also. This PR is for you to merge to staging and deploy to staging. And you are right about the setting the "EXTRA_ENV" setting works perfectly.
https://github.com/proversity-org/edx-platform/pull/732
Please merge and deploy.
